#!/usr/bin/env bash

# Remove any existing files
rm -rf ~/.config/karabiner
rm -rf ~/.config/nvim
rm -rf ~/.config/zsh
rm -rf ~/.config/ghostty
rm -rf ~/.config/opencode
mkdir -p ~/.config/opencode
rm ~/.skhdrc
rm ~/.zshrc

# Create symlinks to files in here
ln -s "$(pwd)/config/karabiner" ~/.config/karabiner
ln -s "$(pwd)/config/nvim" ~/.config/nvim
ln -s "$(pwd)/config/zsh" ~/.config/zsh
ln -s "$(pwd)/config/ghostty" ~/.config/ghostty
ln -s "$(pwd)/config/opencode/AGENTS.md" ~/.config/opencode/AGENTS.md
ln -s "$(pwd)/config/opencode/opencode.json" ~/.config/opencode/opencode.json
ln -s "$(pwd)/.skhdrc" ~/.skhdrc
ln -s "$(pwd)/.zshrc" ~/.zshrc
